### ISSUE TITLE
Issue with multiprocessing on windows

### ISSUE THREAD

**Issue by gainikussainova** [thomas-schillaci/SimPLe#2]
Hi! 
Thank you for creating this library!

I am trying to run it on Windows 10 with GPU running the command:
>python -m simple --env-name SpaceInvaders --agents 1 

However, I get the error:
Traceback (most recent call last):
  File "C:\Users\Gaini\miniconda3\envs\proj\lib\multiprocessing\connection.py", line 313, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gaini\miniconda3\envs\proj\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Gaini\miniconda3\envs\proj\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gaini\Desktop\SimPLe\simple\__main__.py", line 206, in <module>
    simple.train()
  File "C:\Users\Gaini\Desktop\SimPLe\simple\__main__.py", line 147, in train
    self.train_agent_sim_env(epoch)
  File "C:\Users\Gaini\Desktop\SimPLe\simple\__main__.py", line 92, in train_agent_sim_env
    self.simulated_env.env_method('restart', initial_frames, indices=j)
  File "C:\Users\Gaini\Desktop\SimPLe\simple\subproc_vec_env.py", line 361, in env_method
    recv = remote.recv()
  File "C:\Users\Gaini\miniconda3\envs\proj\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\Gaini\miniconda3\envs\proj\lib\multiprocessing\connection.py", line 322, in _recv_bytes
    raise EOFError
EOFError
[W C:\cb\pytorch_1000000000000\work\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)

It should be some problem with multiprocessing. Do you know of a way to fix it?

I am using python 3.7.13

# Name                    Version                   Build  Channel
absl-py                   1.3.0                    pypi_0    pypi
ale-py                    0.7.4                    pypi_0    pypi
alembic                   1.8.1                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
atari-py                  0.2.9                    pypi_0    pypi
atari_py                  0.2.9            py37h7807cd8_0    conda-forge
atomicwrites              1.4.0                      py_0
attrs                     22.1.0           py37haa95532_0
autopage                  0.5.1                    pypi_0    pypi
autorom                   0.4.2                    pypi_0    pypi
autorom-accept-rom-license 0.4.2                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
baselines                 0.1.6                     dev_0    <develop>
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                         mkl
bleach                    5.0.1                    pypi_0    pypi
brotlipy                  0.7.0           py37h2bbff1b_1003
bz2file                   0.98                     pypi_0    pypi
ca-certificates           2022.10.11           haa95532_0
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.9.24        py37haa95532_0
cffi                      1.15.1           py37h2bbff1b_2
chardet                   5.0.0                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3                    pypi_0    pypi
cliff                     3.10.1                   pypi_0    pypi
cloudpickle               1.2.0                    pypi_0    pypi
cmaes                     0.8.2                    pypi_0    pypi
cmd2                      2.4.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
colorlog                  6.7.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cryptography              38.0.1           py37h21b164f_0
cuda                      11.6.2                        0    nvidia
cuda-cccl                 11.6.55                       0    nvidia
cuda-command-line-tools   11.6.2                        0    nvidia
cuda-compiler             11.6.2                        0    nvidia
cuda-cudart               11.6.55                       0    nvidia
cuda-cudart-dev           11.6.55                       0    nvidia
cuda-cuobjdump            11.6.124                      0    nvidia
cuda-cupti                11.6.124                      0    nvidia
cuda-cuxxfilt             11.6.124                      0    nvidia
cuda-libraries            11.6.2                        0    nvidia
cuda-libraries-dev        11.6.2                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight-compute       11.8.0                        0    nvidia
cuda-nvcc                 11.6.124                      0    nvidia
cuda-nvdisasm             11.8.86                       0    nvidia
cuda-nvml-dev             11.6.55                       0    nvidia
cuda-nvprof               11.8.87                       0    nvidia
cuda-nvprune              11.6.124                      0    nvidia
cuda-nvrtc                11.6.124                      0    nvidia
cuda-nvrtc-dev            11.6.124                      0    nvidia
cuda-nvtx                 11.6.124                      0    nvidia
cuda-nvvp                 11.8.87                       0    nvidia
cuda-runtime              11.6.2                        0    nvidia
cuda-sanitizer-api        11.8.86                       0    nvidia
cuda-toolkit              11.6.2                        0    nvidia
cuda-tools                11.6.2                        0    nvidia
cuda-visual-tools         11.6.2                        0    nvidia
cudatoolkit               10.2.89             hb195166_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
dataproperty              0.55.0                   pypi_0    pypi
debugpy                   1.6.4                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
docker-pycreds            0.4.0              pyhd3eb1b0_0
dopamine-rl               3.0.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
etils                     0.9.0                    pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
flask                     2.2.2                    pypi_0    pypi
flatbuffers               22.11.23                 pypi_0    pypi
flit-core                 3.6.0              pyhd3eb1b0_0
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
future                    0.18.2                   pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
gevent                    22.10.2                  pypi_0    pypi
gin-config                0.5.0                    pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
glfw                      2.5.5                    pypi_0    pypi
google-api-core           2.11.0                   pypi_0    pypi
google-api-python-client  2.68.0                   pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.57.0                   pypi_0    pypi
greenlet                  2.0.0                    pypi_0    pypi
grpcio                    1.50.0                   pypi_0    pypi
gunicorn                  20.1.0                   pypi_0    pypi
gym                       0.15.7                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
httplib2                  0.21.0                   pypi_0    pypi
huggingface-hub           0.10.1                   pypi_0    pypi
huggingface-sb3           2.2.4                    pypi_0    pypi
hydra-core                1.0.3                    pypi_0    pypi
idna                      3.4              py37haa95532_0
imageio                   2.22.4                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
importlib-metadata        4.13.0                   pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
importlib_metadata        4.11.3               hd3eb1b0_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.16.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_0
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.4.8                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-core              4.12.0                   pypi_0    pypi
jupyter-server            1.23.3                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
keras                     2.11.0                   pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kfac                      0.2.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kornia                    0.6.8                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libclang                  14.0.6                   pypi_0    pypi
libcublas                 11.11.3.6                     0    nvidia
libcublas-dev             11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufft-dev              10.9.0.58                     0    nvidia
libcurand                 10.3.0.86                     0    nvidia
libcurand-dev             10.3.0.86                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusolver-dev           11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcusparse-dev           11.7.5.86                     0    nvidia
libdeflate                1.8                  h2bbff1b_5
libnpp                    11.8.0.86                     0    nvidia
libnpp-dev                11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvjpeg-dev             11.9.0.86                     0    nvidia
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.20.1               h23ce68f_0
libtiff                   4.4.0                h8a3f274_2
libuv                     1.40.0               he774522_0  
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
mako                      1.2.3                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mbrl                      0.2.0.dev4                dev_0    <develop>
mbstrdecoder              1.1.1                    pypi_0    pypi
mesh-tensorflow           0.1.21                   pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
mock                      4.0.3                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
mujoco                    2.2.1                    pypi_0    pypi
mujoco-py                 2.1.2.14                 pypi_0    pypi
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.2                    pypi_0    pypi
nbconvert                 7.2.6                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
nsight-compute            2022.3.0.22                   0    nvidia
numpy                     1.21.5           py37h7a0a035_3
numpy-base                1.21.5           py37hca35cd5_3
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.0.6                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathtools                 0.1.2              pyhd3eb1b0_1
pathvalidate              2.5.2                    pypi_0    pypi
pbr                       5.11.0                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0            py37hdc2b20a_1
pip                       22.2.2           py37haa95532_0
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
pluggy                    1.0.0            py37haa95532_1
prettytable               3.5.0                    pypi_0    pypi
prometheus-client         0.15.0                   pypi_0    pypi
promise                   2.3              py37haa95532_0
prompt-toolkit            3.0.33                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
py                        1.11.0             pyhd3eb1b0_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pyglet                    1.5.0                    pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyopengl                  3.1.6                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py37haa95532_0
pyperclip                 1.8.2                    pypi_0    pypi
pypng                     0.20220715.0             pypi_0    pypi
pyreadline3               3.4.1                    pypi_0    pypi
pyrsistent                0.19.2                   pypi_0    pypi
pysocks                   1.7.1                    py37_1
pytablewriter             0.64.2                   pypi_0    pypi
pytest                    7.1.2            py37haa95532_0
pytest-parallel           0.1.1                    pypi_0    pypi
python                    3.7.13               h6244533_1
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.13.0          py3.7_cuda11.6_cudnn8_0    pytorch
pytorch-cuda              11.6                 h867d48c_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.6                   pypi_0    pypi
pywin32                   305                      pypi_0    pypi
pywinpty                  2.0.9                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qtconsole                 5.4.0                    pypi_0    pypi
qtpy                      2.3.0                    pypi_0    pypi
requests                  2.28.1           py37haa95532_0
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
rl-zoo3                   1.7.0a2                   dev_0    <develop>
rob831                    0.1.0                     dev_0    <develop>
rsa                       4.9                      pypi_0    pypi
sb3-contrib               1.6.2                    pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
sentry-sdk                1.11.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.5.0           py37haa95532_0
shortuuid                 1.0.11             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1
sk-video                  1.1.10                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlalchemy                1.4.42                   pypi_0    pypi
sqlite                    3.40.0               h2bbff1b_0
stable-baselines3         1.6.2                    pypi_0    pypi
stevedore                 3.5.2                    pypi_0    pypi
sympy                     1.10.1                   pypi_0    pypi
tabledata                 1.3.0                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
tcolorpy                  0.1.2                    pypi_0    pypi
tensor2tensor             1.15.7                   pypi_0    pypi
tensorboard               2.11.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
tensorflow                1.14.0                   pypi_0    pypi
tensorflow-addons         0.18.0                   pypi_0    pypi
tensorflow-datasets       4.7.0                    pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
tensorflow-gan            2.1.0                    pypi_0    pypi
tensorflow-gpu            1.13.1                   pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-intel          2.11.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.28.0                   pypi_0    pypi
tensorflow-metadata       1.11.0                   pypi_0    pypi
tensorflow-probability    0.7.0                    pypi_0    pypi
termcolor                 2.1.1                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
tf-slim                   1.1.0                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1            py37haa95532_0
torchaudio                0.13.0                   pypi_0    pypi
torchvision               0.14.0                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.6.0                    pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typepy                    1.3.0                    pypi_0    pypi
typing-extensions         4.4.0            py37haa95532_0
typing_extensions         4.4.0            py37haa95532_0
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.12          py37haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wandb                     0.13.5             pyhd8ed1ab_0    conda-forge
wasabi                    0.10.1                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        4.0.3                    pypi_0    pypi
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2              py37haa95532_2
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.8                h8cc25b3_0
yaml                      0.2.5                he774522_0
zipp                      3.10.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zope-event                4.5.0                    pypi_0    pypi
zope-interface            5.5.2                    pypi_0    pypi
zstd                      1.5.2                h19a0ad4_0

Another question: is there a way to save the video instead of rendering it?

Thank you!

**Comment by thomas-schillaci** [comment]
Hey @gainikussainova, thank you for your interest in this library!
I haven't been able to reproduce your issue. I can see that you have modified the file `main.py`, are you still running the program using `python -m simple`, and is the code still wrapped in `if __name__ == '__main__':`?

**Comment by gainikussainova** [comment]
Thank you for your response!
I researched a little bit, and I think the problem was in windows; multiprocessing is working not as expected on windows. On Ubuntu it worked!
I have another question, is there any way to save the video, not to render it?

**Comment by gainikussainova** [comment]
Also, --render-evaluation is not working for me, during evaluation nothing is rendered. For training it works as expected. Do you know if it is expected or the possible ways of fixing it?

**Comment by thomas-schillaci** [comment]
I don't plan to add new features to this library.
I've just fixed the `--render-evaluation` bug in c9aef786966f6d939f4d24cb8ed49f5c7d49e8e4, thank you for reporting it!
